config/routes.rb
Hcare::Application.routes.draw do

  get "home/index"
  get "home/callsign"

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get "registrations/profile"
    get "registrations/add_remove_role"
    get "users"=>"userprofiles#index" ,:as=>:user
  end
  resources :userprofiles ,:only=>[:show]
  root to: "home#index"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/userprofile.rb
class Userprofile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :add1, :callsign, :class_user, :efdate, :expdate, :fname, :lname, :state, :zip,:avatar,:remote_avatar_url
  validates :add1, :callsign, :class_user, :efdate, :expdate, :fname, :lname, :state, :zip, presence: true
  mount_uploader :avatar, AvatarUploader
  def full_name
    "#{self.fname} #{self.lname}"
  end
end

app/controllers/userprofiles_controller.rb
class UserprofilesController < ApplicationController
  before_filter :authenticate_user!
	load_resource
	authorize_resource
  def show
  	@user=User.find(params[:user_id])
  	@user_profile=@user.userprofile
  end
  def index
  	@user=current_user
  	@user_profiles=Userprofile.page(params[:page]).per(10)
  end
end

app/helpers/userprofiles_helper.rb
module UserprofilesHelper
	
end

app/views/userprofiles/index.html.haml
.page-header
	%h1 Members
/ .pagination
/ 	= paginate @user_profiles
%table.table.table-striped.table-hover
	%thead
		%tr
			%th Name
			%th Address
			%th State
			%th Zip
			%th Class
	%tbody
	-@user_profiles.each do |profile|
		%tr
			%td
				=link_to profile.full_name, userprofile_path(profile.id,:user_id=>profile.user_id)
			%td=profile.add1
			%td=profile.state
			%td=profile.zip
			%td=profile.class_user
.pagination-position
	= paginate @user_profiles

app/views/userprofiles/show.html.haml
.page-header
	%h1=@user.full_name
%p
	=user_profile_icon(@user)
%p
	%span Email:
	%span
		=@user.email
%p
	%span Callsign:
	%span
		=@user_profile.callsign
%p
	%span Name:
	%span
		=@user.full_name
%p
	%span Address:
	%span
		=@user_profile.add1

%p
	%span State:
	%span
		=@user_profile.state

%p
	%span Zip:
	%span
		=@user_profile.zip

%p
	%span Class:
	%span
		=@user_profile.class_user

%p
	%span efdate:
	%span
		=@user_profile.efdate

%p
	%span expdate:
	%span
		=@user_profile.expdate