config/routes.rb
Hcare::Application.routes.draw do

  get "home/index"
  get "home/callsign"

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get "registrations/profile"
    get "registrations/add_remove_role"
    get "users"=>"userprofiles#index" ,:as=>:user
  end
  resources :userprofiles ,:only=>[:show]
  root to: "home#index"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/views/layouts/partial/_footer.haml
%footer
  .row
    .col-lg-12
      %ul.list-unstyled
        %li.pull-right
          %a{href: "#top"} Back to top
      %p
        Made by
        = succeed "." do
          %a{href: "http://thomaspark.me", rel: "nofollow"} Thomas Park
        = succeed "." do
          %a{href: "mailto:hello@thomaspark.me"} hello@thomaspark.me
      %p
        Code released under the
        = succeed "." do
          %a{href: "https://github.com/thomaspark/bootswatch/blob/gh-pages/LICENSE"} MIT License
      %p
        Based on
        = succeed "." do
          %a{href: "http://getbootstrap.com", rel: "nofollow"} Bootstrap
        = succeed "." do
          %a{href: "http://fortawesome.github.io/Font-Awesome/", rel: "nofollow"} Font Awesome
        = succeed "." do
          %a{href: "http://www.google.com/webfonts", rel: "nofollow"} Google

app/views/layouts/partial/_header_top.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{href: "../"} HCARC - Membership
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav
        / %li.dropdown
        /   %a#themes.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
        /     Themes
        /     %span.caret
        /   %ul.dropdown-menu{"aria-labelledby" => "themes"}
        /     %li
        /       %a{href: "../default/"} Default
        /     %li.divider
        /     %li
        /       %a{href: "../amelia/"} Amelia
        /     %li
        /       %a{href: "../cerulean/"} Cerulean
        /     %li
        /       %a{href: "../cosmo/"} Cosmo
        /     %li
        /       %a{href: "../cyborg/"} Cyborg
        /     %li
        /       %a{href: "../flatly/"} Flatly
        /     %li
        /       %a{href: "../journal/"} Journal
        /     %li
        /       %a{href: "../lumen/"} Lumen
        /     %li
        /       %a{href: "../readable/"} Readable
        /     %li
        /       %a{href: "../simplex/"} Simplex
        /     %li
        /       %a{href: "../slate/"} Slate
        /     %li
        /       %a{href: "../spacelab/"} Spacelab
        /     %li
        /       %a{href: "../superhero/"} Superhero
        /     %li
        /       %a{href: "../united/"} United
        /     %li
        /       %a{href: "../yeti/"} Yeti
        
        -if user_signed_in?
          %li
            =link_to "Signed in as #{current_user.email}. Not you?",user_path
          %li
            = link_to "Sign out", destroy_user_session_path, :method => :delete
        -else
          %li
            =link_to "Sign up",home_callsign_path  
          %li  
            =link_to "Sign in",new_user_session_path

        / %li.dropdown
        /   %a#download.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
        /     Download
        /     %span.caret
        /   %ul.dropdown-menu{"aria-labelledby" => "download"}
        /     %li
        /       %a{href: "./bootstrap.min.css"} bootstrap.min.css
        /     %li
        /       %a{href: "./bootstrap.css"} bootstrap.css
        /     %li.divider
        /     %li
        /       %a{href: "./variables.less"} variables.less
        /     %li
        /       %a{href: "./bootswatch.less"} bootswatch.less
      / %ul.nav.navbar-nav.navbar-right
      /   %li
      /     %a{href: "http://builtwithbootstrap.com/", target: "_blank"} Built With Bootstrap
      /   %li
      /     %a{href: "https://wrapbootstrap.com/?ref=bsw", target: "_blank"} WrapBootstrap

app/views/layouts/partial/_jumberton.html.haml
.bs-docs-section
  .row
    .col-lg-12
      .bs-example
        .jumbotron
          %h1 HCARC - Membership
          %p This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
          %p
            %a.btn.btn-primary.btn-lg Learn more